---
title: "Analyze Final Model"
output: html_notebook
---

```{r}
#read in test.set
test.set = readRDS("predictions-2017.Rda")

```

```{r}
#overall loss
my.loss = ifelse(test.set$pos.win == 1, log(test.set$predictions), log(1-test.set$predictions))
mean(my.loss, na.rm = T) 
my.mse = ifelse(test.set$pos.win == 0, (test.set$predictions)^2, (1-test.set$predictions)^2)
mean(my.mse, na.rm = T)

lock.loss = ifelse(test.set$pos.win == 1, log(test.set$lock.nettleton.prob), log(1-test.set$lock.nettleton.prob))
mean(lock.loss, na.rm = T) 
lock.mse = ifelse(test.set$pos.win == 0, (test.set$lock.nettleton.prob)^2, (1-test.set$lock.nettleton.prob)^2)
mean(lock.mse, na.rm = T)

scrapr.loss = ifelse(test.set$pos.win == 1, log(test.set$Win_Prob), log(1-test.set$Win_Prob))
mean(scrapr.loss, na.rm = T) 
scrapr.mse = ifelse(test.set$pos.win== 0, (test.set$Win_Prob)^2, (1-test.set$Win_Prob)^2)
mean(scrapr.mse, na.rm = T)

mse.regular = as.data.frame(cbind(round(mean(my.mse), 3), round(mean(scrapr.mse, na.rm = T), 3), round(mean(lock.mse, na.rm = T), 3)))
colnames(mse.regular) = c("My model", "nflscrapR model", "Lock and Nettleton model")
rownames(mse.regular) = "Brier score"
saveRDS(mse.regular, file = "mse-regular.Rda")

log.loss.regular = as.data.frame(cbind(round(mean(my.loss), 3), round(mean(scrapr.loss, na.rm = T), 3), round(mean(lock.loss, na.rm = T), 3)))
colnames(log.loss.regular) = c("My model", "nflscrapR model", "Lock and Nettleton model")
rownames(log.loss.regular) = "Log loss"
saveRDS(log.loss.regular, file = "log-loss-regular.Rda")

#loss by quarter
indices.1st = which(test.set$TimeSecs > 2700)
indices.2nd = which(test.set$TimeSecs >1800 & test.set$TimeSecs <= 2700)
indices.3rd = which(test.set$TimeSecs >900 & test.set$TimeSecs <= 1800)
indices.4th = which(test.set$TimeSecs > 0 & test.set$TimeSecs <= 900)
indices.5th = which(test.set$TimeSecs <= 0 & test.set$ot + test.set$ot.kickoff > 0 )

indices.1d = which(test.set$down == "1")
indices.2d = which(test.set$down == "2")
indices.3d = which(test.set$down == "3")
indices.4d = which(test.set$down == "4")
indices.kickoff = which(test.set$kickoff == 1)
indices.xp = which(str_detect(test.set$desc, "extra point|TWO"))

my.mse.quarter = c(mean(my.mse[indices.1st], na.rm=T), mean(my.mse[indices.2nd], na.rm=T), mean(my.mse[indices.3rd], na.rm=T),
  mean(my.mse[indices.4th], na.rm=T), mean(my.mse[indices.5th], na.rm=T))
lock.mse.quarter = c(mean(lock.mse[indices.1st], na.rm=T), mean(lock.mse[indices.2nd], na.rm=T), mean(lock.mse[indices.3rd], na.rm=T),
  mean(lock.mse[indices.4th], na.rm=T), mean(lock.mse[indices.5th], na.rm=T))
scrapr.mse.quarter = c(mean(scrapr.mse[indices.1st], na.rm=T), mean(scrapr.mse[indices.2nd], na.rm=T), mean(scrapr.mse[indices.3rd], na.rm=T),
  mean(scrapr.mse[indices.4th], na.rm=T), mean(scrapr.mse[indices.5th], na.rm=T))
mse.quarter.df = rbind(round(my.mse.quarter,3), round(scrapr.mse.quarter,3), round(lock.mse.quarter,3)) %>% as.data.frame()
colnames(mse.quarter.df) = c("1st Quarter", "2nd Quarter", "3rd Quarter", "4th Quarter", "Overtime")
rownames(mse.quarter.df) = c("My model", "nflscrapR model", "Lock and Nettleton Model")
saveRDS(mse.quarter.df, file = "mse-quarter-df.Rda")

library(ggplot2)
model = c(rep("My model", 4), rep("nflscrapR model", 4), rep("Lock and Nettleton model", 4))
mse.quarter.plot = ggplot() +
  geom_line(aes(x = rep(c(1:4), 3), y = c(my.mse.quarter[1:4], scrapr.mse.quarter[1:4], lock.mse.quarter[1:4]), 
    color = model)) +
  geom_point(aes(x = rep(c(1:4), 3), y = c(my.mse.quarter[1:4], scrapr.mse.quarter[1:4], lock.mse.quarter[1:4]), 
    color = model)) +
  labs(title = "Brier score vs. quarter by model", x = "quarter", y = "Brier score")
saveRDS(mse.quarter.plot, file = "mse-quarter-plot.Rda")
  

my.mse.down = c(mean(my.mse[indices.1d], na.rm=T), mean(my.mse[indices.2d], na.rm=T), mean(my.mse[indices.3d], na.rm=T),
  mean(my.mse[indices.4d], na.rm=T), mean(my.mse[indices.kickoff], na.rm=T), mean(my.mse[indices.xp], na.rm=T))
lock.mse.down = c(mean(lock.mse[indices.1d], na.rm=T), mean(lock.mse[indices.2d], na.rm=T), mean(lock.mse[indices.3d], na.rm=T),
  mean(lock.mse[indices.4d], na.rm=T), mean(lock.mse[indices.kickoff], na.rm=T), mean(lock.mse[indices.xp], na.rm=T))
scrapr.mse.down = c(mean(scrapr.mse[indices.1d], na.rm=T), mean(scrapr.mse[indices.2d], na.rm=T), mean(scrapr.mse[indices.3d], na.rm=T),
  mean(scrapr.mse[indices.4d], na.rm=T), mean(scrapr.mse[indices.kickoff], na.rm=T), mean(scrapr.mse[indices.xp], na.rm=T))
mse.down.df = rbind(round(my.mse.down,3), round(scrapr.mse.down,3), round(lock.mse.down,3)) %>% as.data.frame()
colnames(mse.down.df) = c("1st Down", "2nd Down", "3rd Down", "4th Down", "Kickoff", "Point After Attempt")
rownames(mse.down.df) = c("My model", "nflscrapR model", "Lock and Nettleton Model")
saveRDS(mse.down.df, file = "mse-down-df.Rda")

my.mse.week = rep(NA, 17)
lock.mse.week = my.mse.week
scrapr.mse.week = my.mse.week
for(i in c(1:17)){
  my.mse.week[i] = mean(my.mse[which(test.set$week == i)])
  lock.mse.week[i] = mean(lock.mse[which(test.set$week == i)], na.rm = T)
  scrapr.mse.week[i] = mean(scrapr.mse[which(test.set$week == i)])
}
ggplot() +
  geom_line(linetype = "dashed", aes(x = seq(1, 17, by = 1), y = rep(mse.regular[1,1], 17), color = "overall model Brier score")) +
  geom_point(aes(x = seq(1, 17, by = 1), y = my.mse.week, color = "weekly model Brier score")) + 
  labs(title = "The model's Brier score by week", x = "week", y = "Brier score")


mean(my.mse[indices.kickoff], na.rm=T)
mean(lock.mse[indices.kickoff], na.rm=T)
mean(scrapr.mse[indices.kickoff], na.rm=T)

game.buckets = seq(0.05, 1, by = 0.05)
my.mean.prob = rep(NA, 20)
lock.mean.prob = rep(NA, 20)
scrapr.mean.prob = rep(NA, 20)
my.bucket.win.prob = rep(NA, 20)
lock.bucket.win.prob = rep(NA, 20)
scrapr.bucket.win.prob = rep(NA, 20)

for(i in c(1:20)){
  my.bucket.win.prob[i] = mean(test.set$pos.win[which(test.set$predictions >= game.buckets[i]-.05 &
    test.set$predictions <= game.buckets[i])], na.rm = T)
  lock.bucket.win.prob[i] = mean(test.set$pos.win[which(test.set$lock.nettleton.prob >= game.buckets[i]-.05 &
    test.set$lock.nettleton.prob <= game.buckets[i])], na.rm = T)
  scrapr.bucket.win.prob[i] = mean(test.set$pos.win[which(test.set$Win_Prob >= game.buckets[i]-.05 &
    test.set$Win_Prob <= game.buckets[i])], na.rm = T)
  my.mean.prob[i] = mean(test.set$predictions[which(test.set$predictions >= game.buckets[i]-.05 &
    test.set$predictions <= game.buckets[i])], na.rm = T)
  lock.mean.prob[i] = mean(test.set$lock.nettleton.prob[which(test.set$lock.nettleton.prob >= game.buckets[i]-.05 &
    test.set$lock.nettleton.prob <= game.buckets[i])], na.rm = T)
  scrapr.mean.prob[i] = mean(test.set$Win_Prob[which(test.set$Win_Prob >= game.buckets[i]-.05 &
    test.set$Win_Prob <= game.buckets[i])], na.rm = T)
}

my.calibration.plot = ggplot() +
  geom_line(aes(x = my.mean.prob, y = my.bucket.win.prob, color = "model calibration")) + 
  geom_line(aes(x = seq(0, 1, by = 0.05), y = seq(0, 1, by = 0.05), color = "perfect calibration")) +
  geom_point(aes(x = my.mean.prob, y = my.bucket.win.prob, color = "model calibration")) + 
  labs(title = "Actual vs. predicted win probability for my model", x = "actual win probability", y = "predicted win probability")
lock.calibration.plot = ggplot() +
  geom_line(aes(x = lock.mean.prob, y = lock.bucket.win.prob, color = "model calibration")) + 
  geom_line(aes(x = seq(0, 1, by = 0.05), y = seq(0, 1, by = 0.05), color = "perfect calibration")) +
  geom_point(aes(x = lock.mean.prob, y = lock.bucket.win.prob, color = "model calibration")) + 
  labs(title = "Actual vs. predicted win probability for Lock and Nettleton's model", x = "actual win probability", y = "predicted win probability")
scrapr.calibration.plot = ggplot() +
  geom_line(aes(x = scrapr.mean.prob, y = scrapr.bucket.win.prob, color = "model calibration")) + 
  geom_line(aes(x = seq(0, 1, by = 0.05), y = seq(0, 1, by = 0.05), color = "perfect calibration")) +
  geom_point(aes(x = scrapr.mean.prob, y = scrapr.bucket.win.prob, color = "model calibration")) + 
  labs(title = "Actual vs. predicted win probability for the nflscrapR model", x = "actual win probability", y = "predicted win probability")
grid.arrange(my.calibration.plot, scrapr.calibration.plot, lock.calibration.plot, ncol=1)
plot(lock.bucket.win.prob ~ lock.mean.prob)
plot(scrapr.bucket.win.prob ~ scrapr.mean.prob)


summary(lm(my.mse.week ~ c(1:17)))

#graph probability of new orleans winning for each model
was.no.game = test.set[which((test.set$posteam == "WAS" | test.set$posteam == "NO") & (test.set$DefensiveTeam == "WAS" | test.set$DefensiveTeam == "NO")),]
TimeSecs = rep(was.no.game$TimeSecs, 3)
predictions = c(ifelse(was.no.game$posteam == "NO", was.no.game$predictions, 1-was.no.game$predictions),
  ifelse(was.no.game$posteam == "NO", was.no.game$Win_Prob, 1-was.no.game$Win_Prob),
  ifelse(was.no.game$posteam == "NO", was.no.game$lock.nettleton.prob, 1-was.no.game$lock.nettleton.prob))
model = c(rep("my model", nrow(was.no.game)), rep("nflscrapR model", nrow(was.no.game)), rep("Lock and Nettleton model", nrow(was.no.game)))

ggplot() +
  geom_line(size = 1, aes(x = TimeSecs, y = predictions, color = model)) +
  geom_hline(yintercept = 0.5, color = "gray", linetype = "dashed") +
  scale_x_reverse(breaks = seq(0, 3600, 300)) + 
  geom_vline(xintercept = 900, linetype = "dashed", black) + 
  geom_vline(xintercept = 1800, linetype = "dashed", black) + 
  geom_vline(xintercept = 2700, linetype = "dashed", black) + 
  geom_vline(xintercept = 0, linetype = "dashed", black) + 
  labs(
    x = "Time Remaining (seconds)",
    y = "Win Probability",
    title = "Win Probability of New Orleans Saints During game vs. Washington Redskins by Model",
    subtitle = "Washington Redskins vs. New Orleans Saints",
    caption = "Play by play data from nflscrapR"
  ) + theme_bw()


#graph steelers vs patriots win probability
library(teamcolors)
pit.color = teamcolors$secondary[which(teamcolors$name == "Pittsburgh Steelers")]
det.color = teamcolors$primary[which(teamcolors$name == "Detroit Lions")]

det.pit.game = test.set[which((test.set$posteam == "PIT" | test.set$posteam == "DET") & (test.set$DefensiveTeam == "PIT" | test.set$DefensiveTeam == "DET")),]

TimeSecs = c(det.pit.game$TimeSecs, det.pit.game$TimeSecs)
predictions = c(ifelse(det.pit.game$posteam == "DET", det.pit.game$predictions, 1-det.pit.game$predictions), 
  ifelse(det.pit.game$posteam == "PIT", det.pit.game$predictions, 1-det.pit.game$predictions))
team = c(rep("DET", nrow(det.pit.game)), rep("PIT", nrow(det.pit.game)))

ggplot() +
  geom_line(size = 1, aes(x = TimeSecs, y = predictions, color = team)) +
  geom_hline(yintercept = 0.5, color = "gray", linetype = "dashed") +
  scale_color_manual(labels = c("DET", "PIT"),
                     values = c(det.color, pit.color),
                     guide = FALSE) +
  scale_x_reverse(breaks = seq(0, 3600, 300)) + 
  annotate("text", x = 3000, y = .2, label = "DET", color = det.color, size = 8) + 
  annotate("text", x = 3000, y = .8, label = "PIT", color = pit.color, size = 8) +
  geom_vline(xintercept = 900, linetype = "dashed", black) + 
  geom_vline(xintercept = 1800, linetype = "dashed", black) + 
  geom_vline(xintercept = 2700, linetype = "dashed", black) + 
  geom_vline(xintercept = 0, linetype = "dashed", black) + 
  labs(
    x = "Time Remaining (seconds)",
    y = "Win Probability",
    title = "2017 Regular Season Win Probability Chart",
    subtitle = "Detroit Lions vs. Pittsburgh Steelers",
    caption = "Play by play data from nflscrapR"
  ) + theme_bw()
```